kind: Secret
apiVersion: v1
metadata:
  name: github-oauth-config
  namespace: devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: github
type: Opaque
data:
  id: <clientId | base64>
  secret: <client-secret | base64>