apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devtools-demo
  name: 'devtools-demo'
spec:
  selector:
    matchLabels:
      app: devtools-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: devtools-demo
    spec:
      containers:
        - name: container
          image: >-
            image-registry.openshift-image-registry.svc:5000/devtools-demo/devtools-demo:latest
          ports:
            - containerPort: 8080
              protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
